# 配置端口
server:
  port: 20000
  domain: api.java.crmeb.net
  wechat-api-url:
  wechat-js-api-debug: false
  wechat-js-api-beta: false
  asyncConfig: true

spring:
  profiles:
    #  配置的环境
    active: prod
    #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://数据库IP:3306/crmeb_java?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
    username: 数据库名称
    password: 数据库密码
  redis:
    host: redis地址 #地址
    port: 6379 #端口
    password: redis密码
    timeout: 30000 # 连接超时时间（毫秒）
    database: 0 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

debug: true
logging:
  level:
    io.swagger.*: error
    com.zbjk.crmeb: debug
    org.springframework.boot.autoconfigure: ERROR
  config: classpath:logback-spring.xml
  file:
    path: ./crmeb_log

# mybatis 配置
mybatis-plus:
  # 配置slq打印日志
  configuration:
    log-impl:

#swagger 配置
swagger:
  basic:
    enable: true #是否开启界面
    check: true #是否打开验证
    username: crmeb #访问swagger的账号
    password: crmeb.com #访问swagger的密码